; AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand
; d3d11.dll: 51 named exports (ordinal base 1), 0 ordinal-only
option casemap:none

EXTERN g_aamod_stub_table:QWORD
PUBLIC aamod_shim_unimplemented

.CODE

; resolved-JIT-less trampolines: lea rax, table / jmp qword ptr [rax+8*i]
; RAX is not an argument register in the Win64 ABI, so this is transparent
; (registers RCX/RDX/R8/R9/XMM0-3 and the stack are untouched).

D3D11CreateDeviceForD3D12 PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax]
D3D11CreateDeviceForD3D12 ENDP

D3DKMTCloseAdapter PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+8]
D3DKMTCloseAdapter ENDP

D3DKMTDestroyAllocation PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+16]
D3DKMTDestroyAllocation ENDP

D3DKMTDestroyContext PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+24]
D3DKMTDestroyContext ENDP

D3DKMTDestroyDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+32]
D3DKMTDestroyDevice ENDP

D3DKMTDestroySynchronizationObject PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+40]
D3DKMTDestroySynchronizationObject ENDP

D3DKMTPresent PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+48]
D3DKMTPresent ENDP

D3DKMTQueryAdapterInfo PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+56]
D3DKMTQueryAdapterInfo ENDP

D3DKMTSetDisplayPrivateDriverFormat PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+64]
D3DKMTSetDisplayPrivateDriverFormat ENDP

D3DKMTSignalSynchronizationObject PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+72]
D3DKMTSignalSynchronizationObject ENDP

D3DKMTUnlock PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+80]
D3DKMTUnlock ENDP

D3DKMTWaitForSynchronizationObject PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+88]
D3DKMTWaitForSynchronizationObject ENDP

EnableFeatureLevelUpgrade PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+96]
EnableFeatureLevelUpgrade ENDP

OpenAdapter10 PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+104]
OpenAdapter10 ENDP

OpenAdapter10_2 PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+112]
OpenAdapter10_2 ENDP

CreateDirect3D11DeviceFromDXGIDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+120]
CreateDirect3D11DeviceFromDXGIDevice ENDP

CreateDirect3D11SurfaceFromDXGISurface PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+128]
CreateDirect3D11SurfaceFromDXGISurface ENDP

D3D11CoreCreateDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+136]
D3D11CoreCreateDevice ENDP

D3D11CoreCreateLayeredDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+144]
D3D11CoreCreateLayeredDevice ENDP

D3D11CoreGetLayeredDeviceSize PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+152]
D3D11CoreGetLayeredDeviceSize ENDP

D3D11CoreRegisterLayers PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+160]
D3D11CoreRegisterLayers ENDP

D3D11CreateDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+168]
D3D11CreateDevice ENDP

D3D11CreateDeviceAndSwapChain PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+176]
D3D11CreateDeviceAndSwapChain ENDP

D3D11On12CreateDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+184]
D3D11On12CreateDevice ENDP

D3DKMTCreateAllocation PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+192]
D3DKMTCreateAllocation ENDP

D3DKMTCreateContext PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+200]
D3DKMTCreateContext ENDP

D3DKMTCreateDevice PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+208]
D3DKMTCreateDevice ENDP

D3DKMTCreateSynchronizationObject PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+216]
D3DKMTCreateSynchronizationObject ENDP

D3DKMTEscape PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+224]
D3DKMTEscape ENDP

D3DKMTGetContextSchedulingPriority PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+232]
D3DKMTGetContextSchedulingPriority ENDP

D3DKMTGetDeviceState PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+240]
D3DKMTGetDeviceState ENDP

D3DKMTGetDisplayModeList PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+248]
D3DKMTGetDisplayModeList ENDP

D3DKMTGetMultisampleMethodList PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+256]
D3DKMTGetMultisampleMethodList ENDP

D3DKMTGetRuntimeData PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+264]
D3DKMTGetRuntimeData ENDP

D3DKMTGetSharedPrimaryHandle PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+272]
D3DKMTGetSharedPrimaryHandle ENDP

D3DKMTLock PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+280]
D3DKMTLock ENDP

D3DKMTOpenAdapterFromHdc PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+288]
D3DKMTOpenAdapterFromHdc ENDP

D3DKMTOpenResource PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+296]
D3DKMTOpenResource ENDP

D3DKMTQueryAllocationResidency PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+304]
D3DKMTQueryAllocationResidency ENDP

D3DKMTQueryResourceInfo PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+312]
D3DKMTQueryResourceInfo ENDP

D3DKMTRender PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+320]
D3DKMTRender ENDP

D3DKMTSetAllocationPriority PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+328]
D3DKMTSetAllocationPriority ENDP

D3DKMTSetContextSchedulingPriority PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+336]
D3DKMTSetContextSchedulingPriority ENDP

D3DKMTSetDisplayMode PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+344]
D3DKMTSetDisplayMode ENDP

D3DKMTSetGammaRamp PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+352]
D3DKMTSetGammaRamp ENDP

D3DKMTSetVidPnSourceOwner PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+360]
D3DKMTSetVidPnSourceOwner ENDP

D3DKMTWaitForVerticalBlankEvent PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+368]
D3DKMTWaitForVerticalBlankEvent ENDP

D3DPerformance_BeginEvent PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+376]
D3DPerformance_BeginEvent ENDP

D3DPerformance_EndEvent PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+384]
D3DPerformance_EndEvent ENDP

D3DPerformance_GetStatus PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+392]
D3DPerformance_GetStatus ENDP

D3DPerformance_SetMarker PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+400]
D3DPerformance_SetMarker ENDP

; fallback target for exports the real DLL did not provide:
; returns 0 (a sane failure for HRESULT/BOOL/pointer/MMRESULT)
aamod_shim_unimplemented PROC
    xor eax, eax
    ret
aamod_shim_unimplemented ENDP

END
