// AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand// d3d11.dll: 51 named exports (ordinal base 1), 0 ordinal-only
#include <windows.h>

#define AAMOD_STUB_COUNT 51

extern "C" void* g_aamod_stub_table[AAMOD_STUB_COUNT];
extern "C" void  aamod_shim_unimplemented(void);
void* g_aamod_stub_table[AAMOD_STUB_COUNT] = { 0 };

// name of every proxied export, in stub order
static const char* const kAAModStubNames[AAMOD_STUB_COUNT] = {
    "D3D11CreateDeviceForD3D12",
    "D3DKMTCloseAdapter",
    "D3DKMTDestroyAllocation",
    "D3DKMTDestroyContext",
    "D3DKMTDestroyDevice",
    "D3DKMTDestroySynchronizationObject",
    "D3DKMTPresent",
    "D3DKMTQueryAdapterInfo",
    "D3DKMTSetDisplayPrivateDriverFormat",
    "D3DKMTSignalSynchronizationObject",
    "D3DKMTUnlock",
    "D3DKMTWaitForSynchronizationObject",
    "EnableFeatureLevelUpgrade",
    "OpenAdapter10",
    "OpenAdapter10_2",
    "CreateDirect3D11DeviceFromDXGIDevice",
    "CreateDirect3D11SurfaceFromDXGISurface",
    "D3D11CoreCreateDevice",
    "D3D11CoreCreateLayeredDevice",
    "D3D11CoreGetLayeredDeviceSize",
    "D3D11CoreRegisterLayers",
    "D3D11CreateDevice",
    "D3D11CreateDeviceAndSwapChain",
    "D3D11On12CreateDevice",
    "D3DKMTCreateAllocation",
    "D3DKMTCreateContext",
    "D3DKMTCreateDevice",
    "D3DKMTCreateSynchronizationObject",
    "D3DKMTEscape",
    "D3DKMTGetContextSchedulingPriority",
    "D3DKMTGetDeviceState",
    "D3DKMTGetDisplayModeList",
    "D3DKMTGetMultisampleMethodList",
    "D3DKMTGetRuntimeData",
    "D3DKMTGetSharedPrimaryHandle",
    "D3DKMTLock",
    "D3DKMTOpenAdapterFromHdc",
    "D3DKMTOpenResource",
    "D3DKMTQueryAllocationResidency",
    "D3DKMTQueryResourceInfo",
    "D3DKMTRender",
    "D3DKMTSetAllocationPriority",
    "D3DKMTSetContextSchedulingPriority",
    "D3DKMTSetDisplayMode",
    "D3DKMTSetGammaRamp",
    "D3DKMTSetVidPnSourceOwner",
    "D3DKMTWaitForVerticalBlankEvent",
    "D3DPerformance_BeginEvent",
    "D3DPerformance_EndEvent",
    "D3DPerformance_GetStatus",
    "D3DPerformance_SetMarker",
};

extern "C" unsigned aamod_shim_stub_count(void) { return AAMOD_STUB_COUNT; }

// Fill the jump table from the real DLL. Called from the shim's DllMain
// *before* any exported function of this DLL can be called.
extern "C" void aamod_shim_init_table(HMODULE real)
{
    for (unsigned i = 0; i < AAMOD_STUB_COUNT; ++i) {
        void* p = NULL;
        if (real)
            p = (void*)GetProcAddress(real, kAAModStubNames[i]);
        g_aamod_stub_table[i] = p ? p : (void*)&aamod_shim_unimplemented;
    }
}

// Number of exports that could not be resolved (0 is the healthy case).
extern "C" unsigned aamod_shim_unresolved_count(void)
{
    unsigned n = 0;
    for (unsigned i = 0; i < AAMOD_STUB_COUNT; ++i)
        if (g_aamod_stub_table[i] == (void*)&aamod_shim_unimplemented)
            ++n;
    return n;
}

