// AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand
// d3d11.dll: 51 named exports (ordinal base 1), 0 ordinal-only

#define AAMOD_SHIM_NAME    "d3d11"
#define AAMOD_SHIM_HOOKED  L"d3d11Hooked.dll"
#define AAMOD_SHIM_EXPORTS  51

// this shim also intercepts the entry points below (see src\shim\d3d11\d3d11_intercept.cpp)
#define AAMOD_SHIM_INTERCEPTS 1


