// AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand
// winmm.dll: 180 named exports (ordinal base 2), 1 ordinal-only

#define AAMOD_SHIM_NAME    "winmm"
#define AAMOD_SHIM_HOOKED  L"winmmHooked.dll"
#define AAMOD_SHIM_EXPORTS  180

