; AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand
; winmm.dll: 180 named exports (ordinal base 2), 1 ordinal-only
option casemap:none

EXTERN g_aamod_stub_table:QWORD
PUBLIC aamod_shim_unimplemented

.CODE

; resolved-JIT-less trampolines: lea rax, table / jmp qword ptr [rax+8*i]
; RAX is not an argument register in the Win64 ABI, so this is transparent
; (registers RCX/RDX/R8/R9/XMM0-3 and the stack are untouched).

mciExecute PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax]
mciExecute ENDP

CloseDriver PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+8]
CloseDriver ENDP

DefDriverProc PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+16]
DefDriverProc ENDP

DriverCallback PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+24]
DriverCallback ENDP

DrvGetModuleHandle PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+32]
DrvGetModuleHandle ENDP

GetDriverModuleHandle PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+40]
GetDriverModuleHandle ENDP

OpenDriver PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+48]
OpenDriver ENDP

PlaySound PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+56]
PlaySound ENDP

PlaySoundA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+64]
PlaySoundA ENDP

PlaySoundW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+72]
PlaySoundW ENDP

SendDriverMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+80]
SendDriverMessage ENDP

WOWAppExit PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+88]
WOWAppExit ENDP

auxGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+96]
auxGetDevCapsA ENDP

auxGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+104]
auxGetDevCapsW ENDP

auxGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+112]
auxGetNumDevs ENDP

auxGetVolume PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+120]
auxGetVolume ENDP

auxOutMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+128]
auxOutMessage ENDP

auxSetVolume PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+136]
auxSetVolume ENDP

joyConfigChanged PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+144]
joyConfigChanged ENDP

joyGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+152]
joyGetDevCapsA ENDP

joyGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+160]
joyGetDevCapsW ENDP

joyGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+168]
joyGetNumDevs ENDP

joyGetPos PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+176]
joyGetPos ENDP

joyGetPosEx PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+184]
joyGetPosEx ENDP

joyGetThreshold PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+192]
joyGetThreshold ENDP

joyReleaseCapture PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+200]
joyReleaseCapture ENDP

joySetCapture PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+208]
joySetCapture ENDP

joySetThreshold PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+216]
joySetThreshold ENDP

mciDriverNotify PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+224]
mciDriverNotify ENDP

mciDriverYield PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+232]
mciDriverYield ENDP

mciFreeCommandResource PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+240]
mciFreeCommandResource ENDP

mciGetCreatorTask PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+248]
mciGetCreatorTask ENDP

mciGetDeviceIDA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+256]
mciGetDeviceIDA ENDP

mciGetDeviceIDFromElementIDA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+264]
mciGetDeviceIDFromElementIDA ENDP

mciGetDeviceIDFromElementIDW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+272]
mciGetDeviceIDFromElementIDW ENDP

mciGetDeviceIDW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+280]
mciGetDeviceIDW ENDP

mciGetDriverData PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+288]
mciGetDriverData ENDP

mciGetErrorStringA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+296]
mciGetErrorStringA ENDP

mciGetErrorStringW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+304]
mciGetErrorStringW ENDP

mciGetYieldProc PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+312]
mciGetYieldProc ENDP

mciLoadCommandResource PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+320]
mciLoadCommandResource ENDP

mciSendCommandA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+328]
mciSendCommandA ENDP

mciSendCommandW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+336]
mciSendCommandW ENDP

mciSendStringA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+344]
mciSendStringA ENDP

mciSendStringW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+352]
mciSendStringW ENDP

mciSetDriverData PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+360]
mciSetDriverData ENDP

mciSetYieldProc PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+368]
mciSetYieldProc ENDP

midiConnect PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+376]
midiConnect ENDP

midiDisconnect PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+384]
midiDisconnect ENDP

midiInAddBuffer PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+392]
midiInAddBuffer ENDP

midiInClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+400]
midiInClose ENDP

midiInGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+408]
midiInGetDevCapsA ENDP

midiInGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+416]
midiInGetDevCapsW ENDP

midiInGetErrorTextA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+424]
midiInGetErrorTextA ENDP

midiInGetErrorTextW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+432]
midiInGetErrorTextW ENDP

midiInGetID PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+440]
midiInGetID ENDP

midiInGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+448]
midiInGetNumDevs ENDP

midiInMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+456]
midiInMessage ENDP

midiInOpen PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+464]
midiInOpen ENDP

midiInPrepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+472]
midiInPrepareHeader ENDP

midiInReset PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+480]
midiInReset ENDP

midiInStart PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+488]
midiInStart ENDP

midiInStop PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+496]
midiInStop ENDP

midiInUnprepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+504]
midiInUnprepareHeader ENDP

midiOutCacheDrumPatches PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+512]
midiOutCacheDrumPatches ENDP

midiOutCachePatches PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+520]
midiOutCachePatches ENDP

midiOutClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+528]
midiOutClose ENDP

midiOutGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+536]
midiOutGetDevCapsA ENDP

midiOutGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+544]
midiOutGetDevCapsW ENDP

midiOutGetErrorTextA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+552]
midiOutGetErrorTextA ENDP

midiOutGetErrorTextW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+560]
midiOutGetErrorTextW ENDP

midiOutGetID PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+568]
midiOutGetID ENDP

midiOutGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+576]
midiOutGetNumDevs ENDP

midiOutGetVolume PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+584]
midiOutGetVolume ENDP

midiOutLongMsg PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+592]
midiOutLongMsg ENDP

midiOutMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+600]
midiOutMessage ENDP

midiOutOpen PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+608]
midiOutOpen ENDP

midiOutPrepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+616]
midiOutPrepareHeader ENDP

midiOutReset PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+624]
midiOutReset ENDP

midiOutSetVolume PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+632]
midiOutSetVolume ENDP

midiOutShortMsg PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+640]
midiOutShortMsg ENDP

midiOutUnprepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+648]
midiOutUnprepareHeader ENDP

midiStreamClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+656]
midiStreamClose ENDP

midiStreamOpen PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+664]
midiStreamOpen ENDP

midiStreamOut PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+672]
midiStreamOut ENDP

midiStreamPause PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+680]
midiStreamPause ENDP

midiStreamPosition PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+688]
midiStreamPosition ENDP

midiStreamProperty PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+696]
midiStreamProperty ENDP

midiStreamRestart PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+704]
midiStreamRestart ENDP

midiStreamStop PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+712]
midiStreamStop ENDP

mixerClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+720]
mixerClose ENDP

mixerGetControlDetailsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+728]
mixerGetControlDetailsA ENDP

mixerGetControlDetailsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+736]
mixerGetControlDetailsW ENDP

mixerGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+744]
mixerGetDevCapsA ENDP

mixerGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+752]
mixerGetDevCapsW ENDP

mixerGetID PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+760]
mixerGetID ENDP

mixerGetLineControlsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+768]
mixerGetLineControlsA ENDP

mixerGetLineControlsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+776]
mixerGetLineControlsW ENDP

mixerGetLineInfoA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+784]
mixerGetLineInfoA ENDP

mixerGetLineInfoW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+792]
mixerGetLineInfoW ENDP

mixerGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+800]
mixerGetNumDevs ENDP

mixerMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+808]
mixerMessage ENDP

mixerOpen PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+816]
mixerOpen ENDP

mixerSetControlDetails PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+824]
mixerSetControlDetails ENDP

mmDrvInstall PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+832]
mmDrvInstall ENDP

mmGetCurrentTask PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+840]
mmGetCurrentTask ENDP

mmTaskBlock PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+848]
mmTaskBlock ENDP

mmTaskCreate PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+856]
mmTaskCreate ENDP

mmTaskSignal PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+864]
mmTaskSignal ENDP

mmTaskYield PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+872]
mmTaskYield ENDP

mmioAdvance PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+880]
mmioAdvance ENDP

mmioAscend PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+888]
mmioAscend ENDP

mmioClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+896]
mmioClose ENDP

mmioCreateChunk PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+904]
mmioCreateChunk ENDP

mmioDescend PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+912]
mmioDescend ENDP

mmioFlush PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+920]
mmioFlush ENDP

mmioGetInfo PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+928]
mmioGetInfo ENDP

mmioInstallIOProcA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+936]
mmioInstallIOProcA ENDP

mmioInstallIOProcW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+944]
mmioInstallIOProcW ENDP

mmioOpenA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+952]
mmioOpenA ENDP

mmioOpenW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+960]
mmioOpenW ENDP

mmioRead PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+968]
mmioRead ENDP

mmioRenameA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+976]
mmioRenameA ENDP

mmioRenameW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+984]
mmioRenameW ENDP

mmioSeek PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+992]
mmioSeek ENDP

mmioSendMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1000]
mmioSendMessage ENDP

mmioSetBuffer PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1008]
mmioSetBuffer ENDP

mmioSetInfo PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1016]
mmioSetInfo ENDP

mmioStringToFOURCCA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1024]
mmioStringToFOURCCA ENDP

mmioStringToFOURCCW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1032]
mmioStringToFOURCCW ENDP

mmioWrite PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1040]
mmioWrite ENDP

mmsystemGetVersion PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1048]
mmsystemGetVersion ENDP

sndPlaySoundA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1056]
sndPlaySoundA ENDP

sndPlaySoundW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1064]
sndPlaySoundW ENDP

timeBeginPeriod PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1072]
timeBeginPeriod ENDP

timeEndPeriod PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1080]
timeEndPeriod ENDP

timeGetDevCaps PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1088]
timeGetDevCaps ENDP

timeGetSystemTime PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1096]
timeGetSystemTime ENDP

timeGetTime PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1104]
timeGetTime ENDP

timeKillEvent PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1112]
timeKillEvent ENDP

timeSetEvent PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1120]
timeSetEvent ENDP

waveInAddBuffer PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1128]
waveInAddBuffer ENDP

waveInClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1136]
waveInClose ENDP

waveInGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1144]
waveInGetDevCapsA ENDP

waveInGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1152]
waveInGetDevCapsW ENDP

waveInGetErrorTextA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1160]
waveInGetErrorTextA ENDP

waveInGetErrorTextW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1168]
waveInGetErrorTextW ENDP

waveInGetID PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1176]
waveInGetID ENDP

waveInGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1184]
waveInGetNumDevs ENDP

waveInGetPosition PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1192]
waveInGetPosition ENDP

waveInMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1200]
waveInMessage ENDP

waveInOpen PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1208]
waveInOpen ENDP

waveInPrepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1216]
waveInPrepareHeader ENDP

waveInReset PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1224]
waveInReset ENDP

waveInStart PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1232]
waveInStart ENDP

waveInStop PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1240]
waveInStop ENDP

waveInUnprepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1248]
waveInUnprepareHeader ENDP

waveOutBreakLoop PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1256]
waveOutBreakLoop ENDP

waveOutClose PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1264]
waveOutClose ENDP

waveOutGetDevCapsA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1272]
waveOutGetDevCapsA ENDP

waveOutGetDevCapsW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1280]
waveOutGetDevCapsW ENDP

waveOutGetErrorTextA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1288]
waveOutGetErrorTextA ENDP

waveOutGetErrorTextW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1296]
waveOutGetErrorTextW ENDP

waveOutGetID PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1304]
waveOutGetID ENDP

waveOutGetNumDevs PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1312]
waveOutGetNumDevs ENDP

waveOutGetPitch PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1320]
waveOutGetPitch ENDP

waveOutGetPlaybackRate PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1328]
waveOutGetPlaybackRate ENDP

waveOutGetPosition PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1336]
waveOutGetPosition ENDP

waveOutGetVolume PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1344]
waveOutGetVolume ENDP

waveOutMessage PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1352]
waveOutMessage ENDP

waveOutOpen PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1360]
waveOutOpen ENDP

waveOutPause PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1368]
waveOutPause ENDP

waveOutPrepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1376]
waveOutPrepareHeader ENDP

waveOutReset PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1384]
waveOutReset ENDP

waveOutRestart PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1392]
waveOutRestart ENDP

waveOutSetPitch PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1400]
waveOutSetPitch ENDP

waveOutSetPlaybackRate PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1408]
waveOutSetPlaybackRate ENDP

waveOutSetVolume PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1416]
waveOutSetVolume ENDP

waveOutUnprepareHeader PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1424]
waveOutUnprepareHeader ENDP

waveOutWrite PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+1432]
waveOutWrite ENDP

; fallback target for exports the real DLL did not provide:
; returns 0 (a sane failure for HRESULT/BOOL/pointer/MMRESULT)
aamod_shim_unimplemented PROC
    xor eax, eax
    ret
aamod_shim_unimplemented ENDP

END
