// AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand// version.dll: 17 named exports (ordinal base 1), 0 ordinal-only
#include <windows.h>

#define AAMOD_STUB_COUNT 17

extern "C" void* g_aamod_stub_table[AAMOD_STUB_COUNT];
extern "C" void  aamod_shim_unimplemented(void);
void* g_aamod_stub_table[AAMOD_STUB_COUNT] = { 0 };

// name of every proxied export, in stub order
static const char* const kAAModStubNames[AAMOD_STUB_COUNT] = {
    "GetFileVersionInfoA",
    "GetFileVersionInfoByHandle",
    "GetFileVersionInfoExA",
    "GetFileVersionInfoExW",
    "GetFileVersionInfoSizeA",
    "GetFileVersionInfoSizeExA",
    "GetFileVersionInfoSizeExW",
    "GetFileVersionInfoSizeW",
    "GetFileVersionInfoW",
    "VerFindFileA",
    "VerFindFileW",
    "VerInstallFileA",
    "VerInstallFileW",
    "VerLanguageNameA",
    "VerLanguageNameW",
    "VerQueryValueA",
    "VerQueryValueW",
};

extern "C" unsigned aamod_shim_stub_count(void) { return AAMOD_STUB_COUNT; }

// Fill the jump table from the real DLL. Called from the shim's DllMain
// *before* any exported function of this DLL can be called.
extern "C" void aamod_shim_init_table(HMODULE real)
{
    for (unsigned i = 0; i < AAMOD_STUB_COUNT; ++i) {
        void* p = NULL;
        if (real)
            p = (void*)GetProcAddress(real, kAAModStubNames[i]);
        g_aamod_stub_table[i] = p ? p : (void*)&aamod_shim_unimplemented;
    }
}

// Number of exports that could not be resolved (0 is the healthy case).
extern "C" unsigned aamod_shim_unresolved_count(void)
{
    unsigned n = 0;
    for (unsigned i = 0; i < AAMOD_STUB_COUNT; ++i)
        if (g_aamod_stub_table[i] == (void*)&aamod_shim_unimplemented)
            ++n;
    return n;
}

