// AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand
// version.dll: 17 named exports (ordinal base 1), 0 ordinal-only

#define AAMOD_SHIM_NAME    "version"
#define AAMOD_SHIM_HOOKED  L"versionHooked.dll"
#define AAMOD_SHIM_EXPORTS  17

