; AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand
; version.dll: 17 named exports (ordinal base 1), 0 ordinal-only
option casemap:none

EXTERN g_aamod_stub_table:QWORD
PUBLIC aamod_shim_unimplemented

.CODE

; resolved-JIT-less trampolines: lea rax, table / jmp qword ptr [rax+8*i]
; RAX is not an argument register in the Win64 ABI, so this is transparent
; (registers RCX/RDX/R8/R9/XMM0-3 and the stack are untouched).

GetFileVersionInfoA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax]
GetFileVersionInfoA ENDP

GetFileVersionInfoByHandle PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+8]
GetFileVersionInfoByHandle ENDP

GetFileVersionInfoExA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+16]
GetFileVersionInfoExA ENDP

GetFileVersionInfoExW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+24]
GetFileVersionInfoExW ENDP

GetFileVersionInfoSizeA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+32]
GetFileVersionInfoSizeA ENDP

GetFileVersionInfoSizeExA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+40]
GetFileVersionInfoSizeExA ENDP

GetFileVersionInfoSizeExW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+48]
GetFileVersionInfoSizeExW ENDP

GetFileVersionInfoSizeW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+56]
GetFileVersionInfoSizeW ENDP

GetFileVersionInfoW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+64]
GetFileVersionInfoW ENDP

VerFindFileA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+72]
VerFindFileA ENDP

VerFindFileW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+80]
VerFindFileW ENDP

VerInstallFileA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+88]
VerInstallFileA ENDP

VerInstallFileW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+96]
VerInstallFileW ENDP

VerLanguageNameA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+104]
VerLanguageNameA ENDP

VerLanguageNameW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+112]
VerLanguageNameW ENDP

VerQueryValueA PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+120]
VerQueryValueA ENDP

VerQueryValueW PROC
    lea rax, g_aamod_stub_table
    jmp qword ptr [rax+128]
VerQueryValueW ENDP

; fallback target for exports the real DLL did not provide:
; returns 0 (a sane failure for HRESULT/BOOL/pointer/MMRESULT)
aamod_shim_unimplemented PROC
    xor eax, eax
    ret
aamod_shim_unimplemented ENDP

END
