#!/usr/bin/env python
"""Generate the proxy-DLL sources for an aamod shim.

Given the export table of the *real* system DLL (e.g. System32\\winmm.dll, 181
exports) this writes three files into src/shim/<name>/:

    <name>.def          export list (names + original ordinals)
    <name>_stubs.asm    one 11-byte tail-jump stub per export (ml64)
    <name>_table.cpp    the jump table + resolver + real DLL name

Why stubs instead of .def export forwarders: MSVC's link.exe does **not** emit
forwarders for the `name=module.name` form (verified on VS 2022 14.44 with seven
syntax variants - all LNK2001), so the indirection is done by real code. The jump
table also gives the framework a single place to intercept a proxied call later
(swap a table entry), and it keeps the shim uniform across winmm/version/d3d11.

Usage:
    python gen_shim_def.py winmm [version d3d11 ...]
    python gen_shim_def.py winmm --check     # verify an existing .def matches
    python gen_shim_def.py winmm --report    # show coverage of the game imports
"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SYSTEM32 = os.path.join(os.environ.get("SystemRoot", r"C:\Windows"), "System32")

# The 20 winmm entry points the Astral Ascent executable statically imports.
GAME_WINMM_IMPORTS = [
    "waveInGetNumDevs", "waveInGetDevCapsW", "waveInOpen", "waveInClose",
    "waveOutWrite", "waveInUnprepareHeader", "waveInAddBuffer", "waveInStart",
    "waveInReset", "waveOutReset", "waveOutUnprepareHeader", "waveOutPrepareHeader",
    "waveInPrepareHeader", "timeBeginPeriod", "timeEndPeriod", "waveOutClose",
    "waveOutGetDevCapsW", "waveOutGetErrorTextW", "waveOutOpen", "waveOutGetNumDevs",
]


class PE(object):
    def __init__(self, path):
        with open(path, "rb") as fp:
            self.d = fp.read()
        d = self.d
        e = struct.unpack_from("<I", d, 0x3C)[0]
        if d[e:e + 4] != b"PE\0\0":
            raise ValueError("not a PE file: %s" % path)
        nsec = struct.unpack_from("<H", d, e + 6)[0]
        size_opt = struct.unpack_from("<H", d, e + 20)[0]
        self.opt = e + 24
        magic = struct.unpack_from("<H", d, self.opt)[0]
        if magic == 0x20B:
            dd = self.opt + 112
        elif magic == 0x10B:
            dd = self.opt + 96
        else:
            raise ValueError("unknown optional header magic %#x" % magic)
        self.export_rva, self.export_size = struct.unpack_from("<II", d, dd)
        self.sections = []
        so = self.opt + size_opt
        for i in range(nsec):
            b = so + 40 * i
            nm = d[b:b + 8].rstrip(b"\0").decode("ascii", "replace")
            vsize, va, rawsize, rawptr = struct.unpack_from("<IIII", d, b + 8)
            self.sections.append((nm, va, vsize, rawptr, rawsize))

    def rva_to_off(self, rva):
        for nm, va, vsize, rawptr, rawsize in self.sections:
            if va <= rva < va + max(vsize, rawsize):
                return rawptr + (rva - va)
        return None

    def cstr(self, off):
        end = self.d.index(b"\0", off)
        return self.d[off:end].decode("ascii", "replace")

    def exports(self):
        """-> (list of (name|None, ordinal) sorted by ordinal, base)"""
        o = self.rva_to_off(self.export_rva)
        if o is None:
            return [], 0
        d = self.d
        base = struct.unpack_from("<I", d, o + 16)[0]
        n_funcs = struct.unpack_from("<I", d, o + 20)[0]
        n_names = struct.unpack_from("<I", d, o + 24)[0]
        addr_funcs = struct.unpack_from("<I", d, o + 28)[0]
        addr_names = struct.unpack_from("<I", d, o + 32)[0]
        addr_ords = struct.unpack_from("<I", d, o + 36)[0]
        fo, no, oo = (self.rva_to_off(x) for x in (addr_funcs, addr_names, addr_ords))

        named = {}
        for i in range(n_names):
            nr = struct.unpack_from("<I", d, no + 4 * i)[0]
            ordi = struct.unpack_from("<H", d, oo + 2 * i)[0]
            named[ordi] = self.cstr(self.rva_to_off(nr))

        out = []
        for i in range(n_funcs):
            if struct.unpack_from("<I", d, fo + 4 * i)[0] == 0:
                continue
            out.append((named.get(i), base + i))
        out.sort(key=lambda t: t[1])
        return out, base


def shim_dir(name):
    return os.path.join(ROOT, "src", "shim", name)


def write_shim(name, hooked=None, quiet=False):
    hooked = hooked or ("%sHooked" % name)
    pe = PE(os.path.join(SYSTEM32, name + ".dll"))
    exports, base = pe.exports()
    named = [(nm, od) for nm, od in exports if nm]
    ordinal_only = [od for nm, od in exports if not nm]
    n = len(named)

    d = shim_dir(name)
    if not os.path.isdir(d):
        os.makedirs(d)

    banner = ("AUTO-GENERATED by tools/gen_shim_def.py - do not edit by hand\n"
              "%s.dll: %d named exports (ordinal base %d), %d ordinal-only\n"
              % (name, n, base, len(ordinal_only)))

    # ---- .def -------------------------------------------------------------
    lines = ["; " + banner.replace("\n", "\n; ").rstrip("; ").rstrip(),
             "LIBRARY %s" % name,
             "EXPORTS"]
    for nm, od in named:
        lines.append("    %s @%d" % (nm, od))
    if ordinal_only:
        lines.append("; NOTE: %d ordinal-only export(s) not proxied: %s"
                     % (len(ordinal_only), ", ".join("#%d" % o for o in ordinal_only)))
    with open(os.path.join(d, "%s.def" % name), "w", newline="\r\n") as fp:
        fp.write("\n".join(lines) + "\n")

    # ---- MASM stubs -------------------------------------------------------
    asm = ["; " + banner.replace("\n", "\n; ").rstrip("; ").rstrip(),
           "option casemap:none",
           "",
           "EXTERN g_aamod_stub_table:QWORD",
           "PUBLIC aamod_shim_unimplemented",
           "",
           ".CODE",
           "",
           "; resolved-JIT-less trampolines: lea rax, table / jmp qword ptr [rax+8*i]",
           "; RAX is not an argument register in the Win64 ABI, so this is transparent",
           "; (registers RCX/RDX/R8/R9/XMM0-3 and the stack are untouched)."]
    for i, (nm, od) in enumerate(named):
        off = i * 8
        asm += ["",
                "%s PROC" % nm,
                "    lea rax, g_aamod_stub_table",
                ("    jmp qword ptr [rax]" if off == 0
                 else "    jmp qword ptr [rax+%d]" % off),
                "%s ENDP" % nm]
    asm += ["",
            "; fallback target for exports the real DLL did not provide:",
            "; returns 0 (a sane failure for HRESULT/BOOL/pointer/MMRESULT)",
            "aamod_shim_unimplemented PROC",
            "    xor eax, eax",
            "    ret",
            "aamod_shim_unimplemented ENDP",
            "",
            "END"]
    with open(os.path.join(d, "%s_stubs.asm" % name), "w", newline="\r\n") as fp:
        fp.write("\n".join(asm) + "\n")

    # ---- table + resolver -------------------------------------------------
    tbl = ["// " + banner.replace("\n", "// ").rstrip("/ "),
           "#include <windows.h>",
           "",
           "#define AAMOD_STUB_COUNT %d" % n,
           "",
           "extern \"C\" void* g_aamod_stub_table[AAMOD_STUB_COUNT];",
           "extern \"C\" void  aamod_shim_unimplemented(void);",
           "void* g_aamod_stub_table[AAMOD_STUB_COUNT] = { 0 };",
           "",
           "// name of every proxied export, in stub order",
           "static const char* const kAAModStubNames[AAMOD_STUB_COUNT] = {"]
    for nm, od in named:
        tbl.append("    \"%s\"," % nm)
    tbl += ["};",
            "",
            "extern \"C\" unsigned aamod_shim_stub_count(void) { return AAMOD_STUB_COUNT; }",
            "",
            "// Fill the jump table from the real DLL. Called from the shim's DllMain",
            "// *before* any exported function of this DLL can be called.",
            "extern \"C\" void aamod_shim_init_table(HMODULE real)",
            "{",
            "    for (unsigned i = 0; i < AAMOD_STUB_COUNT; ++i) {",
            "        void* p = NULL;",
            "        if (real)",
            "            p = (void*)GetProcAddress(real, kAAModStubNames[i]);",
            "        g_aamod_stub_table[i] = p ? p : (void*)&aamod_shim_unimplemented;",
            "    }",
            "}",
            "",
            "// Number of exports that could not be resolved (0 is the healthy case).",
            "extern \"C\" unsigned aamod_shim_unresolved_count(void)",
            "{",
            "    unsigned n = 0;",
            "    for (unsigned i = 0; i < AAMOD_STUB_COUNT; ++i)",
            "        if (g_aamod_stub_table[i] == (void*)&aamod_shim_unimplemented)",
            "            ++n;",
            "    return n;",
            "}",
            ""]
    with open(os.path.join(d, "%s_table.cpp" % name), "w", newline="\r\n") as fp:
        fp.write("\n".join(tbl) + "\n")

    # ---- per-shim config header ------------------------------------------
    cfg = ["// %s" % banner.replace("\n", "\n// ").rstrip("/ "),
           "#define AAMOD_SHIM_NAME    \"%s\"" % name,
           "#define AAMOD_SHIM_HOOKED  L\"%s.dll\"" % hooked,
           "#define AAMOD_SHIM_EXPORTS  %d" % n,
           ""]
    with open(os.path.join(d, "%s_config.h" % name), "w", newline="\r\n") as fp:
        fp.write("\n".join(cfg) + "\n")

    if not quiet:
        print("[gen_shim_def] %s: %d named exports -> %s.*" % (name, n, name))
        if ordinal_only:
            print("[gen_shim_def] %s: skipping %d ordinal-only export(s): %s"
                  % (name, len(ordinal_only), ", ".join("#%d" % o for o in ordinal_only)))
        if name == "winmm":
            have = set(nm for nm, _ in named)
            missing = [f for f in GAME_WINMM_IMPORTS if f not in have]
            print("[gen_shim_def] game winmm imports: %d/%d covered%s"
                  % (len(GAME_WINMM_IMPORTS) - len(missing), len(GAME_WINMM_IMPORTS),
                     "" if not missing else "  MISSING: %s" % ", ".join(missing)))
    return d


def check_shim(name):
    path = os.path.join(shim_dir(name), "%s.def" % name)
    asm_path = os.path.join(shim_dir(name), "%s_stubs.asm" % name)
    if not os.path.isfile(path):
        print("[gen_shim_def] %s does not exist" % path)
        return 1
    pe = PE(os.path.join(SYSTEM32, name + ".dll"))
    exports, _ = pe.exports()
    expected = set(nm for nm, _ in exports if nm)

    got = set()
    with open(path, "r") as fp:
        for line in fp:
            line = line.strip()
            if not line or line.startswith(";") or line.startswith("LIBRARY") \
                    or line.startswith("EXPORTS"):
                continue
            got.add(line.split()[0])

    stubs = 0
    if os.path.isfile(asm_path):
        with open(asm_path, "r") as fp:
            for line in fp:
                if line.strip().endswith("PROC"):
                    stubs += 1
        stubs -= 1                       # aamod_shim_unimplemented is not an export

    missing = sorted(expected - got)
    extra = sorted(got - expected)
    ok = not missing and not extra and stubs == len(got)
    print("[gen_shim_def] %s: %d exports in DLL, %d in .def, %d stubs -> %s"
          % (name, len(expected), len(got), stubs, "OK" if ok else "MISMATCH"))
    if missing:
        print("  missing: %s" % ", ".join(missing[:20]))
    if extra:
        print("  extra  : %s" % ", ".join(extra[:20]))
    return 0 if ok else 1


def main(argv):
    names = [a for a in argv[1:] if not a.startswith("--")]
    mode = "--check" if "--check" in argv else None
    if not names:
        names = ["winmm"]
    rc = 0
    for name in names:
        if mode == "--check":
            rc |= check_shim(name)
        else:
            write_shim(name)
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
